# Site settings
language:               ""
title:                  "Brauntrutta"
description:            "Personal Website"
google-verification:    ""
default_hero_image:     "v1528641635/dan-bass-fly-ski-chicken-outside.jpg"

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
#  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "/.idea/"

# Plugins
# Add plugins in the Gemfile

# Conversion
incremental:      true

# Serving
#url:            "https://danbraun.github.io/f6-jekyll/"
baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

highlighter:      rouge
