# Site settings
language:               ""
title:                  "Daniel Braun"
description:            "Personal Website"
google-verification:    ""
default_hero_image:     "c_scale,w_2000/v1528856400/IMG_2653.jpg"

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
#  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "/.idea/"

# Plugins
# Add plugins in the Gemfile

# Conversion
incremental:      true

# Serving
url:            "https://gracious-mclean-7b4215.netlify.com"
baseurl:        "" # does not include hostname

# Outputting
permalink:        pretty
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

highlighter:      rouge

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jemoji

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

category-images:
  running: 'c_scale,h_2000/v1562075471/shoes.jpg'
  cycling: 'v1561995508/Superior%20Vistas/IMG_20190622_124227.jpg'
  recipes: 'c_scale,w_2000/v1529521584/Kale%20Salad/IMG_20180619_213145.jpg'

cloudinary:
  cloud_name: brauntrutta
  only_prod: false
  verbose: true
  origin_url: https://res.cloudinary.com
  presets:
    default:
      min_width: 320
      max_width: 1200
      fallback_max_width: 800
      steps: 5
      sizes: "(max-width: 450px) 160px, 90vw"