# Site settings
language:               ""
title:                  "Daniel Braun"
description:            "Personal Website"
google-verification:    ""
default_hero_image:     "v1528641635/dan-bass-fly-ski-chicken-outside.jpg"

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
#  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "/.idea/"

# Plugins
# Add plugins in the Gemfile

# Conversion
incremental:      true

# Serving
url:            "http://127.0.0.1.xip.io:3000"
baseurl:        "" # does not include hostname

# Outputting
permalink:        pretty
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

highlighter:      rouge

plugins:
  - jekyll-archives
  - jekyll-paginate

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'